In [16]:
import numpy as np
import matplotlib.pyplot as plt
import random as rd



In [34]:
a=np.array([1,2,3])
print(a)
print([1,2])
print(a.shape)
print(a[:,None])
print(a[None,:])
b=a[:,None]-a[None,:]
print(b, b.shape)
print(b[1,2])
print(a[None,:,None])
c=np.array([[1,2,3],[4,5,6]])
print(c[:,None], c[:,:,None])
print(c[:,None]-c[:,:,None])

#le slicing sur le tableau se fait de dimension en dimension en commençant par la 
#plus grande (ie le nombre d'élements que contiennent les crochets les plus extérieurs)
#et à chaque dimension on donne une instruction. : signifie parcourir les élements et 
# None crée une nouvelle dimension (ie rajoute des crochets autour de l'objet consideré à ce moment)



[1 2 3]
[1, 2]
(3,)
[[1]
 [2]
 [3]]
[[1 2 3]]
[[ 0 -1 -2]
 [ 1  0 -1]
 [ 2  1  0]] (3, 3)
-1
[[[1]
  [2]
  [3]]]
[[[1 2 3]]

 [[4 5 6]]] [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
[[[ 0  1  2]
  [-1  0  1]
  [-2 -1  0]]

 [[ 0  1  2]
  [-1  0  1]
  [-2 -1  0]]]


In [28]:
# les bornes pour le tirage au sort initial
mass_max = 3.
    
x_min, x_max = -10., 10.
y_min, y_max = -10., 10.

speed_max = 1.


In [36]:
def init_problem(N):
    masses=np.array([rd.uniform(10**(-43),mass_max) for i in range(N)])
    positions=np.array([[rd.uniform(x_min,x_max) for i in range(N)],[rd.uniform(y_min,y_max) for i in range(N)]])
    vitesses=np.array([[rd.uniform(0,speed_max) for i in range(N)],[rd.uniform(0,speed_max) for i in range(N)]])
    return masses,positions,vitesses

#j'aurai pu utiliser la fonction np.random.uniforme qui prend en argument les bornes pour chauque dimension
# sous forme d'un tabelau à la bonne dimension et la shape du tableau à créer

masses,positions,speeds=init_problem(10)

try:
    assert masses.shape == (10,) and positions.shape == speeds.shape == (2, 10)
    print("OK")
except:
    print("KO")


OK


In [52]:
# for your convenience

def init3():
    # first element is sun-like: heavy, at the center, and no speed
    masses = np.array([3, 1, 1], dtype=float)
    positions = np.array([
        [0, 5, -5], 
        [0, 1, -1]], dtype=float)
    speeds = np.array([
        [0, -1, 1], 
        [0, 0, 0]], dtype=float)
    return masses, positions, speeds
masses,positions,speeds=init3()

In [56]:
def forces(masses, positions, G=1.0):
    diff=positions[:,:,None]-positions[:,None,:]
    dist=np.linalg.norm(diff,axis=0)
    np.fill_diagonal(dist,1)
    coeffs=G*masses[:,None]*masses
    forces=diff*coeffs/(dist**3)
    force_tot=np.sum(forces,1)
    return force_tot


In [57]:
# pour tester, voici les valeurs attendues avec la config prédéfinie

masses, positions, speeds = init3()

f = forces(masses, positions)

# should be true
# np.all(np.isclose(f, np.array([
#     [ 0.        , -0.12257258,  0.12257258],
#     [ 0.        , -0.02451452,  0.02451452]])))


In [66]:
def simulate(masses,positions,speeds,dt=0.1, nb_steps=100):
    traj=np.ones((nb_steps,2,3))
    for i in range(nb_steps):
        accel=forces/masses
        speeds=speeds + accel*dt
        positions= positions + speeds*dt
        traj[i]=positions
    return traj

    
    

In [67]:
# pour tester

SMALL_STEPS = 4

s = simulate(masses, positions, speeds, nb_steps=SMALL_STEPS)

try:
    if s.shape == (SMALL_STEPS, 2, 3):
        print("shape OK")
except Exception as exc:
    print(f"OOPS {type(exc)} {exc}")

# pour tester: should be true

# first step
positions1 = s[1]




TypeError: unsupported operand type(s) for /: 'function' and 'float'